"""init ocr checkup schema

Revision ID: 97a644712a37
Revises: 
Create Date: 2026-06-23 00:48:51.810214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a644712a37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkup_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkup_metric_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('metric_code', sa.String(length=50), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reference_min', sa.Float(), nullable=True),
    sa.Column('reference_max', sa.Float(), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('raw_text', sa.String(length=200), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkup_metric_results_record_id'), 'checkup_metric_results', ['record_id'], unique=False)
    op.create_table('checkup_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('measured_at', sa.DateTime(), nullable=True),
    sa.Column('ocr_status', sa.String(length=20), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('analysis_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkup_records_file_hash'), 'checkup_records', ['file_hash'], unique=False)
    op.create_index(op.f('ix_checkup_records_user_id'), 'checkup_records', ['user_id'], unique=False)
    op.create_unique_constraint("uq_checkup_records_user_file_hash", "checkup_records", ["user_id", "file_hash"])
    op.create_table('meal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocr_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raw_result_url', sa.String(length=500), nullable=True),
    sa.Column('parsed_field_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_jobs_record_id'), 'ocr_jobs', ['record_id'], unique=False)
    op.create_index(op.f('ix_ocr_jobs_user_id'), 'ocr_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ocr_jobs_user_id'), table_name='ocr_jobs')
    op.drop_index(op.f('ix_ocr_jobs_record_id'), table_name='ocr_jobs')
    op.drop_table('ocr_jobs')
    op.drop_table('meal_records')
    op.drop_index(op.f('ix_checkup_records_user_id'), table_name='checkup_records')
    op.drop_index(op.f('ix_checkup_records_file_hash'), table_name='checkup_records')
    op.drop_constraint("uq_checkup_records_user_file_hash", "checkup_records", type_="unique")
    op.drop_table('checkup_records')
    op.drop_index(op.f('ix_checkup_metric_results_record_id'), table_name='checkup_metric_results')
    op.drop_table('checkup_metric_results')
    op.drop_table('checkup_files')
    # ### end Alembic commands ###
