"""인증 도메인 정책 상수.

이메일 인증 코드·로그인 잠금 등 비즈니스 규칙 수치를 한 곳에서 관리한다.
SMTP 메일 템플릿(`smtp_email_client.py`)의 "10분 후 만료" 문구와 일치시킨다.
"""

VERIFICATION_CODE_LENGTH = 6
VERIFICATION_CODE_EXPIRE_MINUTES = 10
VERIFICATION_MAX_ATTEMPTS = 5
VERIFICATION_RESEND_COOLDOWN_SECONDS = 60

VERIFICATION_TOKEN_EXPIRE_MINUTES = 30

LOGIN_MAX_FAILURES = 5
LOGIN_LOCKOUT_MINUTES = 15
